//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HereToSlayImplementation.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HereToSlayImplementation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        static public class DrT
        {
            static List<System.Drawing.Bitmap> CardImages = new List<Bitmap>();
            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Back
            {
                get
                {
                    object obj = ResourceManager.GetObject("Back", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Diagnosis_Evil_
            {
                get
                {
                    object obj = ResourceManager.GetObject("Diagnosis Evil!", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Ego_Whip
            {
                get
                {
                    object obj = ResourceManager.GetObject("Ego Whip", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Enthralled_Thrall
            {
                get
                {
                    object obj = ResourceManager.GetObject("Enthralled Thrall", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Id_Insinuation
            {
                get
                {
                    object obj = ResourceManager.GetObject("Id Insinuation", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Info
            {
                get
                {
                    object obj = ResourceManager.GetObject("Info", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Just_A_Nibble
            {
                get
                {
                    object obj = ResourceManager.GetObject("Just A Nibble", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Mind_Blast
            {
                get
                {
                    object obj = ResourceManager.GetObject("Mind Blast", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Mind_Games
            {
                get
                {
                    object obj = ResourceManager.GetObject("Mind Games", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap PhD_in_Psychology
            {
                get
                {
                    object obj = ResourceManager.GetObject("PhD in Psychology", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Puppet_Therapy
            {
                get
                {
                    object obj = ResourceManager.GetObject("Puppet Therapy", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Receptionist
            {
                get
                {
                    object obj = ResourceManager.GetObject("Receptionist", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Relax_After_Work
            {
                get
                {
                    object obj = ResourceManager.GetObject("Relax After Work", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Sip_Tea
            {
                get
                {
                    object obj = ResourceManager.GetObject("Sip Tea", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Superego_Whip
            {
                get
                {
                    object obj = ResourceManager.GetObject("Superego Whip", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap Tell_Me_About_Your_Mother
            {
                get
                {
                    object obj = ResourceManager.GetObject("Tell Me About Your Mother", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static List<System.Drawing.Bitmap> MakeTheList()
            {
                CardImages.Add(Diagnosis_Evil_);
                CardImages.Add(Puppet_Therapy);
                CardImages.Add(Id_Insinuation);
                CardImages.Add(Enthralled_Thrall);
                CardImages.Add(PhD_in_Psychology);
                CardImages.Add(Superego_Whip);
                CardImages.Add(Sip_Tea);
                CardImages.Add(Receptionist);
                CardImages.Add(Relax_After_Work);
                CardImages.Add(Ego_Whip);
                CardImages.Add(Just_A_Nibble);
                CardImages.Add(Mind_Blast);
                CardImages.Add(Mind_Games);
                CardImages.Add(Tell_Me_About_Your_Mother);
                return CardImages;
            }
        }

        static public class minscBoo
        {

            static List<System.Drawing.Bitmap> CardImages = new List<Bitmap>();
            internal static System.Drawing.Bitmap back1
            {
                get
                {
                    object obj = ResourceManager.GetObject("back", resourceCulture);
                    Console.WriteLine($"{ResourceManager.ToString()}");
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap info1
            {
                get
                {
                    object obj = ResourceManager.GetObject("info", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Boo_What_Do_We_Do
            {
                get
                {
                    object obj = ResourceManager.GetObject("Boo, What Do We Do", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Favoured_Frienemies
            {
                get
                {
                    object obj = ResourceManager.GetObject("Favoured Frienemies", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Go_Fpr_The_Eyes_Boo
            {
                get
                {
                    object obj = ResourceManager.GetObject("Go For The Eyes, Boo!!", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Justice_Waits_For_No_One
            {
                get
                {
                    object obj = ResourceManager.GetObject("Justice Waits For No One", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Krydle_and_Shandie
            {
                get
                {
                    object obj = ResourceManager.GetObject("Krydle and Shandie", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Minscs_Mighty_Mount
            {
                get
                {
                    object obj = ResourceManager.GetObject("Minsc's Mighty Mount", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Pale_Priestess_Nerys
            {
                get
                {
                    object obj = ResourceManager.GetObject("Pale Priestess Nerys", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Scouting_Outing
            {
                get
                {
                    object obj = ResourceManager.GetObject("Scouting Outing", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Someone_Hold_My_Rodent
            {
                get
                {
                    object obj = ResourceManager.GetObject("Someone Hold My Rodent", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Squeaky_Wheel_Gets_The_Kick
            {
                get
                {
                    object obj = ResourceManager.GetObject("Squeaky Wheel Gets The Kick", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Swapportunity
            {
                get
                {
                    object obj = ResourceManager.GetObject("Swapportunity", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Time_To_Punch_Evil
            {
                get
                {
                    object obj = ResourceManager.GetObject("Time To Punch Evil!", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Twice_The_Smiting
            {
                get
                {
                    object obj = ResourceManager.GetObject("Twice The Smiting", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static System.Drawing.Bitmap Wrap_It_Up
            {
                get
                {
                    object obj = ResourceManager.GetObject("Wrap It Up", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            internal static List<System.Drawing.Bitmap> MakeTheList()
            {
                CardImages.Add(Krydle_and_Shandie);
                CardImages.Add(Squeaky_Wheel_Gets_The_Kick);
                CardImages.Add(Justice_Waits_For_No_One);
                CardImages.Add(Wrap_It_Up);
                CardImages.Add(Go_Fpr_The_Eyes_Boo);
                CardImages.Add(Minscs_Mighty_Mount);
                CardImages.Add(Time_To_Punch_Evil);
                CardImages.Add(Someone_Hold_My_Rodent);
                CardImages.Add(Pale_Priestess_Nerys);
                CardImages.Add(Boo_What_Do_We_Do);
                CardImages.Add(Twice_The_Smiting);
                CardImages.Add(Favoured_Frienemies);
                CardImages.Add(Scouting_Outing);
                CardImages.Add(Swapportunity);
                return CardImages;
            }
        }

    }
}
